version: '3'

services:
  mongodb:
    image: mongo:4.4
    restart: on-failure
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: editeur_service_db
    volumes:
      - db:/data/db/
      - ./docker/mongoData:/data/db/

  ms-editeur:
    build:
      context: ./editeur-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  db: